### PR TITLE
Android Compatibility

### PR DESCRIPTION
**Pull request by Alia5**
- Fixed rendering
- Fixed Touch input
- Support Android Soft Keyboard
- Fixed Android backspace button

screen

### CODE REVIEW

**Comment by eliasdaler** [comment]
That looks amazing, thanks!

**Comment by aggsol** [comment]
@Alia5 Do you build it like [described in the wiki](https://github.com/SFML/SFML/wiki/Tutorial:-Building-SFML-for-Android)?

**Comment by Alia5** [comment]
@aggsol I built SFMLlike described in your linked article yes (even on windows)
It is to note that for full c++11 support (afterwards) you have to compile SFML with libc++_shared (or static) and use android-ndk-r12b to compile SFML.
(I just didn't install SFML to anywhere, made that by hand...)

You then can use the latest and greatest NDK bundles with AndroidStudio.

To get SFML working in AndroidStudio without dirty hacks or experimental build tools, have a look at this:
https://github.com/Alia5/SFML_AndroidStudio

**Comment by Alia5** [comment]
BTW: I wouldn't recommend running ImGui on Android on small devices without scaling.
I work with (and use it as my daily diver) a 6.4" phone and the UI is just barely large enough.

**Pull request merged**
