### PR TITLE
Added IMGUI_SFML_IMGUI_DEMO option to CMake build

### PR DESCRIPTION
**Pull request by dubgron**
Enabling it will result in compiling imgui_demo.cpp file, that contains e.g. ImGui::ShowDemoWindow function, which is useful for new users.

Resolves: #121

### CODE REVIEW

**Comment by eliasdaler** [comment]
Hello
I think you should add it as `option` in main CMakeLists.txt file and in FindImGui.cmake have `IMGUI_DEMO_SOURCE` variable defined. And then:

```cmake
if (IMGUI_SFML_IMGUI_DEMO)
    list(APPEND IMGUI_SOURCES ${IMGUI_SFML_IMGUI_DEMO})
endif()

add_library(ImGui-SFML
  imgui-SFML.cpp
  ${IMGUI_SOURCES}
)

...
```

**Comment by dubgron** [comment]
Hi,
I thought about doing it that way, but in my opinion using CMake's generator expressions results in nicer code. But if you prefer it your way I made a new commit.

**Comment by eliasdaler** [comment]
Please also add this in the root CMakeLists:

```diff
option(IMGUI_SFML_FIND_SFML "Use find_package to find SFML" ON)
+ option(IMGUI_SFML_IMGUI_DEMO "Build imgui_demo.cpp" OFF)
```

The `option` is a good way of documenting that some variables can be set by user, to differentiate them from internal script variables. It's a bad practice to have non-cache variables being set by user externally.

**Comment by dubgron** [comment]
Good point.

**Comment by eliasdaler** [comment]
Thanks, merged!

**Pull request merged**
