### PR TITLE
Add android compatibility

### PR DESCRIPTION
**Pull request by Alia5**

### CODE REVIEW

**Comment by eliasdaler** [comment]
Wow, that looks pretty neat, thanks!

I don't want to test it, I believe that it should work. Any screens of it running on Android? :)

**Comment by Alia5** [comment]
Ahh, don't merge it yet. I just noticed that I shouldn't use ```#ifdef ANDROID``` since there are x86 Android devices with proper OpenGL...

I'll update quickly...

Will share screens when fixed ;)

**Comment by eliasdaler** [comment]
Oops. :D
Should I revert it for now and merge it later?

**Comment by Alia5** [comment]
Yup please...

**Pull request merged**
