### PR TITLE
Update imgui-SFML.h

### PR DESCRIPTION
**Pull request by Epholys**
I'd like to merge this little modification.

When building my project I had some issues from multiple `#include` directives.
Adding `#pragma once` at the top of `imgui-SFML.h` solves this issue.

Thanks for this project!

### CODE REVIEW

**Comment by aggsol** [comment]
I would recommend using normal include guards for various reasons see: https://en.wikipedia.org/wiki/Pragma_once

**Comment by Epholys** [comment]
Thanks for the tip @aggsol, you are right!

**Comment by eliasdaler** [comment]
While I like `pragma once` more, I think that include guards are more universal, and I already had to abandon some things I like for portability. Thanks!

**Comment by aggsol** [comment]
@eliasdaler as a benchmark I would say that every SFML does for prtability can't be that bad :-)

**Comment by eliasdaler** [comment]
@aggsol agreed.

**Pull request merged**
